[package]
name = "meowscript"
version = "0.1.0"
edition = "2021"

[lib]
name = "meowscript"
path = "src/lib.rs"

[[bin]]
name = "meow"
path = "src/bin.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
